---

- name: Installing passlib package for python {{ ansible_python_version[0] }}
  apt:
    pkg: "{{ passlib_package[ansible_python_version[0]] }}"
    state: present


- name: Creating htpasswd folder
  file:
    dest: "{{ htpasswd_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
